sudo: required # 跑 docker 需要最高權限

# step1. Tell Travis we need a copy of docker running
services:
  - docker

# step2. Build our image using Dockerfile.dev
before_install:
  - docker build -t ruru0403/react-docker-app -f Dockerfile.dev .

# step3. Tell Travis how to run test suite
script: # 所有要執行的指令
  - docker run -e CI=true ruru0403/react-docker-app npm run test

# step4. Tell travis how to deploy our code to AWS
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "react-app-docker" # 在 elasticbeanstalk 上創建的 app 的名字
  env: "Reactappdocker-env" # elasticbeanstalk 上創建的環境名
  bucket_name: "elasticbeanstalk-ap-northeast-1-964218111192" # Travis 會將 github 上的 code 抓下來放在 S3
  bucket_path: "react-app-docker" # 存放 code 的 S3 的名稱
  on:
    branch: master # 只有當 code push 到 master 分支上時才執行部署
  access_key_id: $AWS_ACCESS_KEY # 加入連線 AWS 所需的金鑰
  secret_access_key:
    secure: "$AWS_SECRET_KEY"