version: '3'
services:
  web:
    build: 
      context: . # image 從哪裡拉下檔案
      dockerfile: Dockerfile.dev # docker file 的位置
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app # . -> the current folder outside the container, /app -> the current folder inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true # for windows，程式無法自動更新時
  testWeb:
    build: 
      context: . # image 從哪裡拉下檔案
      dockerfile: Dockerfile.dev # docker file 的位置
    volumes:
      - /app/node_modules
      - .:/app # . -> the current folder outside the container, /app -> the current folder inside the container
    command: ["npm", "run", "test"]